- name: Update web servers
  hosts: webservers
  remote_user: opc

  tasks:
    - name: Ensure nginx is at latest version
      ansible.builtin.yum:
        name: nginx
        state: latest
      become: yes
    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes